**Python for data analysis (Pandas)**

In [60]:
# Importing the Pandas library
import pandas as pd

In [65]:
# The df variable will be responsible for storing the dataframe
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/MOCK_DATA.csv", sep=',')

In [66]:
# Viewing the first five lines 
df.head()

   id first_name  ...    gender       ip_address
0   1       Risa  ...  Bigender   137.217.16.178
1   2       Tine  ...   Agender   107.112.220.68
2   3    Hershel  ...  Bigender  249.246.253.235
3   4      Moina  ...      Male   251.32.166.234
4   5   Angelico  ...   Agender     85.43.211.90

[5 rows x 6 columns]

In [77]:
# Rename the columns 
df = df.rename(columns={"id":"Code", "first_name":"First Name", "last_name":"Last Name", "email":"E-mail", "gender":"Gender", "ip_address":"IP address"})

In [29]:
# Number of rows and columns 
df.shape

(1000, 1)

In [78]:
# Name of columns
df.columns

Index(['Code', 'First Name', 'Last Name', 'E-mail', 'Gender', 'IP address'], dtype='object')

In [79]:
# Types of data
df.dtypes

Code           int64
First Name    object
Last Name     object
E-mail        object
Gender        object
IP address    object
dtype: object

In [80]:
# Last lines
df.tail()

     Code  First Name  ...       Gender       IP address
995   996        Matt  ...     Bigender  250.251.124.139
996   997         Vin  ...      Agender    87.160.43.201
997   998        Gaby  ...  Genderqueer    137.30.90.177
998   999     Tatiana  ...   Polygender     1.61.161.193
999  1000  Georgeanna  ...   Non-binary  110.208.218.146

[5 rows x 6 columns]

In [81]:
# Last three lines
df.tail(3)

     Code  First Name  ...       Gender       IP address
997   998        Gaby  ...  Genderqueer    137.30.90.177
998   999     Tatiana  ...   Polygender     1.61.161.193
999  1000  Georgeanna  ...   Non-binary  110.208.218.146

[3 rows x 6 columns]

In [85]:
# Statistical information about the data (this dataframe is not suitable for this view)
df.describe()

              Code
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [95]:
# Return only single values ​​of the selected variable
df["Gender"].unique()

array(['Bigender', 'Agender', 'Male', 'Non-binary', 'Genderfluid',
       'Polygender', 'Genderqueer', 'Female'], dtype=object)

In [97]:
# The variable Male takes the records of all gender that which also in the dataframe
Male = df.loc[df["Gender"] == "Male"]
Male.head()

    Code First Name  ... Gender       IP address
3      4      Moina  ...   Male   251.32.166.234
12    13      Tamas  ...   Male  213.252.145.255
21    22     Leonie  ...   Male   221.134.46.198
24    25    Halette  ...   Male    20.229.79.192
26    27    Branden  ...   Male    203.15.135.48

[5 rows x 6 columns]

In [98]:
Male["Gender"].unique()

array(['Male'], dtype=object)

In [106]:
# Grouping by gender
df.groupby("Gender")["First Name"].nunique()

Gender
Agender        113
Bigender       128
Female         139
Genderfluid    139
Genderqueer    100
Male           131
Non-binary     122
Polygender     122
Name: First Name, dtype: int64